# Generated by Django 5.2.14 on 2026-05-27 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_name_per_user',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
