# Generated by Django 5.2.14 on 2026-05-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_category_unique_category_name_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='payments/receipts/'),
        ),
    ]
