# Generated by Django 5.2.14 on 2026-05-28 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentmethod_payment_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('scheduled_confirmation', 'Confirmação de agendamento'), ('reminder_3_days', 'Lembrete de 3 dias'), ('reminder_1_day', 'Lembrete de 1 dia')], max_length=32)),
                ('scheduled_date', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='payments.payment')),
            ],
            options={
                'ordering': ('-sent_at',),
                'constraints': [models.UniqueConstraint(fields=('payment', 'kind', 'scheduled_date'), name='unique_payment_notification_per_date')],
            },
        ),
    ]
