# Generated by Django 5.2.14 on 2026-05-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymentnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentnotification',
            name='kind',
            field=models.CharField(choices=[('scheduled_confirmation', 'Confirmação de agendamento'), ('reminder_1_day', 'Lembrete de 1 dia')], max_length=32),
        ),
    ]
