# Generated by Django 5.2.14 on 2026-05-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_paymentnotification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentnotification',
            name='kind',
            field=models.CharField(choices=[('scheduled_confirmation', 'Confirmação de agendamento'), ('reminder_1_day', 'Lembrete de 1 dia'), ('reminder_due_today', 'Lembrete do dia')], max_length=32),
        ),
    ]
