# Generated by Django 5.2.14 on 2026-08-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_payment_is_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='installment_group',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='installment_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='installment_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
