# Generated by Codex on 2026-07-14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_refresh_insight_texts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlySpendingGoal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "alert_threshold",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(50, "50%"), (75, "75%"), (90, "90%")],
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_spending_goal",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="SpendingGoalNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_key", models.CharField(max_length=7)),
                ("threshold", models.PositiveSmallIntegerField(choices=[(50, "50%"), (75, "75%"), (90, "90%")])),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="dashboard.monthlyspendinggoal",
                    ),
                ),
            ],
            options={
                "ordering": ("-sent_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="spendinggoalnotification",
            constraint=models.UniqueConstraint(
                fields=("goal", "period_key", "threshold"),
                name="unique_spending_goal_notification_per_month",
            ),
        ),
    ]
