# Generated by Codex on 2026-07-14

from datetime import date

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def fill_existing_goal_months(apps, schema_editor):
    MonthlySpendingGoal = apps.get_model("dashboard", "MonthlySpendingGoal")
    today = timezone.localdate()
    current_month = date(today.year, today.month, 1)
    MonthlySpendingGoal.objects.filter(period_month__isnull=True).update(period_month=current_month)


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_monthlyspendinggoal_spendinggoalnotification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyspendinggoal",
            name="period_month",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(fill_existing_goal_months, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="monthlyspendinggoal",
            name="period_month",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="monthlyspendinggoal",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monthly_spending_goals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlyspendinggoal",
            constraint=models.UniqueConstraint(
                fields=("user", "period_month"),
                name="unique_monthly_spending_goal_per_user_month",
            ),
        ),
    ]
