# Generated by Django 5.2.14 on 2026-08-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_monthlyspendinggoal_period_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyspendinggoal',
            name='alert_thresholds',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
