# Generated by Django 5.2.14 on 2026-05-27 22:10

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, validators=[accounts.validators.validate_phone]),
        ),
    ]
